FROM dockerfile/java:oracle-java8
MAINTAINER mschuboth
EXPOSE 8080
ADD build/microservice-quickstart-1.0.jar /data/microservice-quickstart-1.0.jar
CMD ["java", "-jar", "spring-boot-maven-docker.jar"] 
