FROM dockerfile/java:oracle-java8
MAINTAINER mschuboth
ADD microservice-quickstart-1.0.jar /opt/microservice-quickstart-1.0.jar
EXPOSE 8080
WORKDIR /opt/microservice-quickstart-1.0
CMD ["java", "-jar", "microservice-quickstart-1.0.jar"]
